---
- name: Deploy Flask App on EC2 using Docker
  hosts: ec2
  become: yes

  tasks:
    - name: Copy Docker image tar to EC2
      copy:
        src: ../flask-app/flask-app.tar
        dest: /home/ubuntu/flask-app.tar

    - name: Load Docker image
      command: docker load -i /home/ubuntu/flask-app.tar

    - name: Remove old container if exists
      command: docker rm -f flask-container
      ignore_errors: yes

    - name: Run Flask container
      command: docker run -d --name flask-container -p 5000:5000 flask-app

